### ISSUE TITLE
'IATI data updated' data not consistent with update dates contained within the dataset

### ISSUE THREAD

**Issue by dalepotter** [IATI/ckanext-iati#125]
The British Red Cross dataset [BRC Grants to partners](https://iatiregistry.org/dataset/gb-chc-220949-activities) is reporting an 'IATI data updated' time of `2016-09-08 00:00`. 

![image](https://user-images.githubusercontent.com/8247168/27484182-2adef59a-5820-11e7-9fd5-5128b3a21f6a.png)

NOTE this was manually edited by @amy-silcock this morning (in order to test the edit functionality), but before 11am this morning it showed `2015-09-08 00:00`.

However, the data in the [dataset file](http://www.redcross.org.uk/~/media/BritishRedCross/Documents/Where%20we%20work/BRC-iati-all-6-9-2016.xml) itself shows `generated-datetime="2017-06-01T05:00:04.9169433+01:00"`:
![image](https://user-images.githubusercontent.com/8247168/27484327-bfb9aa20-5820-11e7-8d7e-766b3b76f623.png)

Could we check that the harvester is correctly updating this metadata?  This may also be related to #117 which highlighted issue in identifying and storing metadata related to IATI Standard version numbers.

**Comment by newkdukem** [comment]
Updating the metadata is handled by the archiver module of the extension. In the case of 'IATI data updated', as well as 'IATI standard version' the archiver occasionally does not update the the metadata. We're still not sure what is causing this because it occurs intermittently. But we are investigating this intensively in order to find the culprit.

**Comment by PetyaKangalova** [comment]
@newkdukem Thanks for the update.

I have been contacted by UNICEF with question about 'IATI data updated' which is not showing correctly. I know that this is an on-going issue that you re investigating, but wanted to check whether you can fix the metadata update for [UNICEF](https://www.iatiregistry.org/publisher/unicef) and can also use it as an example for your investigation and hopefully shed more light on why the issue occurs intermittently?


Uploaded XML: http://files.unicef.org/transparency/countrydata/iatiActivity_Afghanistan.xml
```
<iati-activities version="2.01" generated-datetime="2017-07-27T14:57:37Z">
<iati-activity last-updated-datetime="2017-07-26T00:00:00" xml:lang="en" default-currency="USD" hierarchy="1" linked-data-uri="">
<iati-identifier>41122-Afghanistan-0060/A0/06/008/001</iati-identifier>
```
 
![image](https://user-images.githubusercontent.com/24607542/28866720-b280970a-776b-11e7-9e25-fee6c1fdda59.png)

**Comment by newkdukem** [comment]
@PetyaKangalova a solution for the inconsistent 'IATI data updated' metadata is under development. I will provide additional comments concerning the status.

**Comment by PetyaKangalova** [comment]
@newkdukem Has there been any progress with this issue? We continue getting emails from publishers asking about the IATI data updated.

Many thanks,
Petya

**Comment by newkdukem** [comment]
Changes were made on the staging portal and the iati-archiver was manually run. The metadata should now be consistent with the actual xml files.

**Comment by andylolz** [comment]
Worth noting (I didn’t know this, anyway) that the `generated-datetime` is *not* the thing that’s used here for the “IATI data updated” metadata. Instead, it’s the most recent `last-updated-datetime` for an `iati-activity` or `iati-organisation`.

**Comment by newkdukem** [comment]
@andylolz correct, and in the previously mentioned [xml](http://www.redcross.org.uk/%7E/media/BritishRedCross/Documents/Where%20we%20work/BRC-iati-all-6-9-2016.xml), there is no `last-updated-datetime` field.

**Comment by andylolz** [comment]
> and in the previously mentioned [xml](http://www.redcross.org.uk/~/media/BritishRedCross/Documents/Where%20we%20work/BRC-iati-all-6-9-2016.xml), there is no last-updated-datetime field.

Good spot, yes! And the UNICEF example [mentioned above](https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-319618326) is [correct on staging](https://iati-staging.ckan.io/dataset/unicef-afghanistan) – 2017-09-05T00:00:00 is the most recent `last-updated-datetime`.

I’m just running a script to check the rest. I’ve submitted one small pull request (#140) that makes a tiny tweak to standardise IATI data updated timestamps, and ensure the seconds are preserved.

**Comment by andylolz** [comment]
I compared the ‘IATI data updated’ timestamps with the `last-updated-datetime`s in IATI data from the *live* registry (which I happened to have a local copy of). So not [apples and oranges](https://en.wikipedia.org/wiki/Apples_and_oranges), but not apples and apples either.

They overwhelmingly match (roughly 4267/4449 correct), but there’s still a few errors in there. For instance, there’s a bunch of examples where the date is correct but the time is wrong: https://iati-staging.ckan.io/dataset/unitedstates-ly

In this case, that’s because the minute is zero, so the whole time is thrown away. I think the logic here is wrong:
https://github.com/ViderumGlobal/ckanext-iati/blob/f6539246169597e874cf0e4ade83e2268724a2fd/ckanext/iati/archiver.py#L229-L231

Anyway, #140 should fix that.

Apart from that, dates for DFID and AFD are consistently wrong. In the case of DFID, I think it’s because they have updated their data since the last time the archiver ran (it looks like they do it monthly at the end of the month.) [Here’s an example.](https://iati-staging.ckan.io/dataset/dfid-ke) In the case of AFD, it’s just because the staging server links to totally different data. So again, that’s something separate. [Here’s an example.](https://iati-staging.ckan.io/dataset/afd-cg)

In sum, this looks fine! (but you need to make a change to ensure times are always correct.)

**Comment by amy-silcock** [comment]
Great @andylolz , thanks again for looking into this! @newkdukem and Viderum would you be able to follow up on this please?

**Comment by newkdukem** [comment]
Thank you @andylolz for the PR. This is merged and deployed on the staging portal now.

**Comment by dalepotter** [comment]
Thanks for the update @newkdukem - I've just looked at staging portal for the British Red Cross dataset that was originally used to demonstrate this problem. However it seems that this is not yet fixed.

The [staging portal](https://iati-staging.ckan.io/dataset/gb-chc-220949-activities) shows:

![image](https://user-images.githubusercontent.com/8247168/31280764-54845e3a-aaa5-11e7-983e-0e8d066520b1.png)

However, the dataset shows:

![image](https://user-images.githubusercontent.com/8247168/31280702-1c1ebbe4-aaa5-11e7-8cec-09fbe27065d0.png)

**Comment by andylolz** [comment]
@dalepotter: That’s because of this: https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-333689554. @newkdukem spotted that that BRC dataset doesn’t contain any `last-updated-datetime`s, so that’s why the data updated date hasn’t changed. https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-333774219.

**Comment by hayfield** [comment]
[As noted](https://github.com/IATI/IATI-Datastore/issues/268#issuecomment-337123175) by @markbrough in IATI/IATI-Datastore#268, the [Netherlands Ministry of Foreign Affairs activities file 2016-2017](https://iatiregistry.org/dataset/minbuza_nl-activities20162017) does not have the correct metadata. The data file does, however, contain the attributes noted by @andylolz in https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-334875054.

**Comment by andylolz** [comment]
@hayfield did you read https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-334059352? I did an exhaustive check of the timestamps on the staging site, and posted my findings there.

**Comment by andylolz** [comment]
I did a full download of data from staging, and for each dataset, compared the maximum `last-updated-datetime` in the data with the one on the staging registry. There were only 30 occasions where these didn’t match:
https://gist.github.com/andylolz/00d6a98eb9de48df557350b0682ae252

At least some of these are due to dodgy data e.g. dates in the future, which [the archiver ignores](https://github.com/andylolz/ckanext-iati/blob/299a32b3/ckanext/iati/archiver.py#L220). Others are wrong by less than a minute.

## Short term:

There are still a few more anomalies that I’m unsure about, but on the whole this is a massive improvement, and it would be great to get it onto production as soon as possible.

## Longer term:

I don’t think “IATI data updated” should rely on publisher-entered dates (which are sometimes clearly incorrect. See: `last-updated-datetime`s in the future.) It should probably be diffing old and new versions of each file, and updating to today whenever something changes.

**Comment by JGulic** [comment]
The archiver that is running on the staging portal has the latest code changes that were made in order to resolve the issues with the metadata (like IATI date updated, or IATI standard version).
These changes are not deployed on production and that is the reason that there are inconsistencies with the metadata on the staging and the production portal.
I would agree that we need to push the code changes about the metadata and the archiver on production in order to avoid issues like this one.
@dalepotter if you can agree on this decision too, I'll make sure to push the changes to production as soon as we get an answer from you.

**Comment by andylolz** [comment]
> that is the reason that there are inconsistencies with the metadata on the staging and the production portal.

Just to note: in https://github.com/ViderumGlobal/ckanext-iati/issues/125#issuecomment-337561248 I’m comparing staging with staging, not staging with production. I don’t know what the explanation for the inconsistencies are here, but there are very few inconsistencies.

**Comment by dalepotter** [comment]
@JGulic yes please do deploy to production as soon as you can. For bug fixes such as this I would suggest standard practice should be to deploy straight to production.

**Comment by andylolz** [comment]
@JGulic is this live now?

I just checked and the issue still exists on the live registry… But not sure if that’s because a) the change hasn’t been pushed yet, or b) the archiver hasn’t run yet.

**Comment by andylolz** [comment]
@JGulic @newkdukem bump – what’s the status on this?

I ask because this is a dependency for the IATI datastore, and it’s currently causing it to be very broken, which in turn is having an adverse affect on partner country aid management systems.

I tested again today, and I’m still seeing weird “IATI data updated” dates in the metadata on the production registry, that don’t match the underlying data.

Thanks!

**Comment by JGulic** [comment]
@andylolz we are preparing the changes for production and retesting everything again, before we move there. We want to make sure that once the update is setup on production everything will run smoothly and there will be no problems anymore with the issues that we were having.
When the deployment process is done I'll post a comment here to let everyone know about it.

**Comment by andylolz** [comment]
Thanks @JGulic – that makes a lot of sense. When do you think that will be done? Do you have an ETA for pushing this live? Thanks!

**Comment by JGulic** [comment]
@andylolz everything should be ready and setup on production by Monday afternoon

**Comment by JGulic** [comment]
@dalepotter the code is setup on production and it has successfully passed during the weekend and updated the resources. @andylolz you can let us know if everything is working good with the IATI Datastore

**Comment by andylolz** [comment]
> @andylolz you can let us know if everything is working good with the IATI Datastore

Don’t know about the IATI Datastore yet, but I can tell you that the dates in the registry metadata look fixed! :tada: :tada: :tada:

**Comment by PetyaKangalova** [comment]
@JGulic  I have been contacted by a publisher- [Asian Development Bank](https://www.iatiregistry.org/publisher/asdb)- asking why the dates have not updated? See screenshots below.


![image](https://user-images.githubusercontent.com/24607542/32223110-05c0e1c2-be34-11e7-8021-f0865bfa04db.png)
![image](https://user-images.githubusercontent.com/24607542/32223089-ed888b78-be33-11e7-92de-c76dfd1f30b2.png)

They have updated their data on 26-10-2017 and seems that the Registry hasn't refreshed and picked up their data? Could this be linked with the Registry being down last Friday? Also, why is the IATI-Registry- updated 2017-10-28? It seems that for some IATI publishers the Registry refreshed today while for others only on Saturday. This shouldn't be the case. Could you look into this?

**Comment by andylolz** [comment]
@PetyaKangalova: The date shown in the registry metadata is not the one you highlight – it’s this one:

![screen shot 2017-10-31 at 13 47 15](https://user-images.githubusercontent.com/464193/32227205-9db3213a-be42-11e7-810d-db224dffe417.png)

That is: it’s the most recent `last-updated-datetime` for a `iati-activity`. That’s by design: i.e. it’s working as expected (for some definition of “expected”).

To use a favourite @yohannaloucheur turn of phrase, there appears to be “stratospheric levels of confusion” around this particular bit of metadata. Perhaps what’s needed here is:

 1. some justification for the current approach, and
 2. some public documentation to explain it.

**Comment by PetyaKangalova** [comment]
@andylolz  Thanks for this and I indeed noticed that it was confusion on my side before responding to the Asian Development Bank. Apologies for not updating the Github post straightaway. I agree that we need agreement on what the date is for.  In my experience so far, the **IATI data updated** date  is mainly used by publishers who want to make sure and check that their data has successfully updated.  In that case `the generated-datetime `will be more useful.  In the way that this is currently set up, something in the lines of last-updated activity data might be more intuitive.

 My question here was relating to **IATI Registry updated** - 
![image](https://user-images.githubusercontent.com/24607542/32270435-d0f0611a-beed-11e7-91cf-748fe3ca3724.png)
@JGulic  isn't this supposed to show today's date for all publishers as the Registry refreshes daily?

**Comment by JGulic** [comment]
@PetyaKangalova this is connected with the way the archiver runs. While the archiver is going through the datasets, it checks the resources. We are keeping a hash to the resource, and we are checking against this hash if the resource has been updated or not. If the resource stayed the same, there is no data to be updated, the archiver skips the updating of the package hence the date in IATI registry updated will not change. This doesn't mean that the archiver didn't pass successfully through the specific dataset (resource), just means that nothing has been changed in the meantime.

We can easily modify this behaviour and save the data every time the archiver passes through a resource and update the IATI registry updated field. But have one note in mind that this will increase the time that the archiver requires to run through the resources. The archiver operation depends on the update operations that it has to preform.

**Comment by PetyaKangalova** [comment]
@JGulic Thanks for the clarification on 'IATI registry updated' field. It does make sense to me that the archiver will pass the data only if there are updates.  The question I raised is also separate to the initial Github issues raised in here, so we can discuss separately, but many thanks for the clarification.

 As I understand, the existing Github issue related to a bug with the 'IATI data updated' field has been fixed and tested. Could you please confirm that in here and close the issue if that is the case?

**Comment by JGulic** [comment]
@PetyaKangalova yes, we can close this issue and open new issues if needed

**Comment by andylolz** [comment]
> While the archiver is going through the datasets, it checks the resources. We are keeping a hash to the resource, and we are checking against this hash if the resource has been updated or not

It’s a bit beside the point… but due to a bug the archiver doesn’t actually work like this. See #157 and the corresponding fix #154.

**Comment by goranmaxim** [comment]
#154 is merged and deployed.

**Comment by dalepotter** [comment]
Following discussion with @PetyaKangalova this issue appears to be ongoing in isolated incidents. A new issue will be created with the specific details of the latest problem, for the benefit of the new suppliers.
