### ISSUE TITLE
User experience enhancement - Visual design improvement

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#351]
One of the user experience enhancement recommendations was to improve the visual design of the registration form to enhance the readability and scannability of the form. 

### **Requirements:**

**1. Appropriate padding between fields and sections.**
	- Add a larger break between field groups so it's clearly visible the separation. Field groups are defined in https://github.com/IATI/ckanext-iati/issues/350

**2. Remove field information from below each field to unclutter the page.**
	- Add ? mark icon next to labels that need information about the field. 
	- When user hovers the ? show info of the field.
	- The following fields should have ? and extra information:
	_Publisher Id:_ This will be the unique identifier for the publisher. Where possible use a short abbreviation of your organisation's name. For example: "fcdo", "worldbank".
	_Publisher Name:_ The name of the organisation publishing the data.
	_IATI Organisation Identifier:_ The organisation identifier used in the IATI XML files to identify the reporting organisation. For more information please go to How to create your IATI organisation identifier. iatistandard.org/en/guidance/preparing-organisation/organisation-account/how-to-create-your-iati-organisation-identifier/
	_Source:_ Primary - publishers authorised to report their own (or associated organisations') data. Secondary - publishers reporting the activities of other organisations.
	_License:_ See https://github.com/IATI/ckanext-iati/issues/353
	_Country:_ The country in which the publisher is legally incorporated. Multilateral and regional organisations may choose a region at the bottom of the list.
	_Image URL:_ Link to an image to be used as the publisher logo (Optimum size: 200 x 120 px)
	_Contact Email:_ IATI is an open data standard and the email provided here will be visible to others via the IATI Registry.
	_Description:_ General description of publisher's role and activities.
	_Timeliness of Data:_ How soon after data is captured and available internally will data be published?
	_Units of Aid:_ How is an activity defined e.g. projects and programmes, or some other structure? Do you have multi-tiered project structures e.g. projects and sub-projects or components? At which level/s do you intend to publish details?).
	_Segmentation of Published Data:_ Is IATI data published in separate files per country or region?
	_Data Definitions and References:_ Links to guides, explanations, codelists on the publisher's own site that clarify their data.
	_Field Exclusions:_ What fields recommended in the standard do you never use - and for what reason.
	_Record Exclusions:_ What are your policies for excluding particular activities, or parts of an activity's data?
	_Thresholds:_ What are the thresholds below which data or whole activities are not published?
	_Other Constraints:_ Other policies or circumstances that restrict your full compliance with the standard.
	_Data Quality:_ Publisher's comment on the status and accuracy of the data - audited/verified, operational/sub to change, etc
	_User Interface:_ Will IATI data be accessible for end users through an existing or a new user interface on your website?
	_User Interface URL:_ The URL to the website where your IATI data is accessible.

**3. Add examples in field forms similar to the Image URL field.**
	- _Email:_ add the following example: e.g. name@example.com
	- _Website:_ add the following example: e.g. http://www.mywebsite.com
	- _Image URL:_ update the current example to: e.g. http://example.com/my-image.jpg
	- _First published date:_ update the current example to: e.g. 2020-10-20
	- _User Interface URL:_ add the following example: e.g. http://www.myuserinterface.com
![image](https://user-images.githubusercontent.com/74558657/113997116-bd422880-984f-11eb-9b7c-ba5dccdf8ed8.png)

**4. Add real-time (while user types) validation for the following fields:**
	- _Publisher Id:_ must be at least three characters long and lower case. Can include letters, numbers and also - (dash) and _ (underscore).
	- _IATI Organisation Identifier:_ should only accept letters, numbers and - (take into consideration existing ID's that already might contain invalid characters)
	- _Email:_ should be a valid email address.
	- _Website:_ should be a valid website URL.
	- _Image URL:_ should be a valid website URL.
	- _First published date:_ should be a valid date format.
	- _User Interface URL:_ should be a valid website URL.

**5. Update error messages to match the above validation.** Currently some error messages do not match the validation e.g. Publisher ID error message states it must be 2 characters long, the extra information below the textbox states it should be 3 characters long.

**Comment by gtkChop** [comment]
@andreaszenasidi 

1. Appropriate padding between fields and sections. - 
2. Remove field information from below each field to unclutter the page.
1 day

Add examples in field forms similar to the Image URL field. - 0.5 day
Add real-time (while user types) validation for the following fields: - 2.5 days
Update error messages to match the above validation - 0.5 day

Total: 4,5 to 5 days

**Comment by gtkChop** [comment]
@andreaszenasidi 

**1.  Appropriate padding between fields and sections.**
Done

**2. Remove field information from below each field to unclutter the page.**
- Hover text is not possible, because there are inks in helper text. If hover is enabled users cannot click on the links in the helper text

![Screen Shot 2021-11-19 at 19 56 08](https://user-images.githubusercontent.com/32418025/142676476-b7afaaba-775b-4fba-94bc-a56b3a534e69.png)

**3. Add examples in field forms similar to the Image URL field.**
Done

**4. Add real-time (while user types) validation for the following fields:**

Question: Do we need this feature? This will be a load to the database because for every keystroke we have to check if the value exists in the database. Moreover, our registration form is open anyone can use it. I believe the current validation is more efficient.


**5. Update error messages to match the above validation.** 
Done

**Comment by andreaszenasidi** [comment]
@gtkChop I think there is a different branch on staging now, I cant see any of the UX Enhancement changes.

**Comment by jodiegardiner** [comment]
Should be able to see this now

**Comment by andreaszenasidi** [comment]
@gtkChop 

**2. Remove field information from below each field to unclutter the page.**
If hover is not possible, can we still add the **?** and then when users click it then the box is displayed with the information? Clicking it again will make the box disappear.  

**3. Add examples in field forms similar to the Image URL field.**
I can't see the examples.

**4. Add real-time (while user types) validation for the following fields:**
All these field validations only require Regex check not hitting the DB so it should be feasible. We are not validating if the fields already exist.

**5. Update error messages to match the above validation.**
The validation error message doesn't match the help text error message. For example:
![image](https://user-images.githubusercontent.com/74558657/146343478-6a7539eb-edb5-4b6b-a85e-15aa98e01429.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

**2. Remove field information from below each field to unclutter the page.**
Done

**3. Add examples in field forms similar to the Image URL field.**
```
- Email: add the following example: e.g. name@example.com
- Website: add the following example: e.g. http://www.mywebsite.com
- Image URL: update the current example to: e.g. http://example.com/my-image.jpg
- First published date: update the current example to: e.g. 2020-10-20
- User Interface URL: add the following example: e.g. http://www.myuserinterface.com
```

**4. Add real-time (while user types) validation for the following fields:**
Added validation wherever possible.

**5. Update error messages to match the above validation.**
Done

**Comment by andreaszenasidi** [comment]
**2. Remove field information from below each field to unclutter the page.**
Looks great!

**3. Add examples in field forms similar to the Image URL field.**
Looks good.

**4. Add real-time (while user types) validation for the following fields.**
There is no real-time validation added to any of the fields. When you type in invalid characters no error message is showing up only when you try to create the publisher by clicking the button. If this is not possible to be implemented we can remove this requirement. 

All error messages should show up in red (see screengrab 2). At the moment they show up as screengrab 1.
**SCREENGRAB 1:**
![image](https://user-images.githubusercontent.com/74558657/148972094-68ca3b90-625a-4d31-9f24-93a5e9a417ed.png)
**SCREENGRAB 2:**
![image](https://user-images.githubusercontent.com/74558657/148972143-81d2719c-7fe2-45e4-9953-c4fd623e9990.png)


**New issues found:**
1. The IATI Organisation Identifier filed has no validation. I was able to create a new publisher using **"** as an IATI Organisation identifier. When we create a new publisher, it should only accept letters, numbers and - However, for old publishers with existing identifiers with invalid characters the form shouldn't give an error. 
![image](https://user-images.githubusercontent.com/74558657/148973301-b27459ed-b710-4600-8c41-3e29031728bc.png)

2. I also noticed that the User edit page shows up with the new layout, however, the header of the sections are not aligned well.
![image](https://user-images.githubusercontent.com/74558657/148972692-e4fe6c9e-d503-4066-b972-d517654e5110.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

Fixed issues other than validation color

Currently, there are two validation in place

- Client-side validation (html form validation) yellow in color.
- Server-side validation red in color.


Client-side validation color is decided by the browser and we do not have control over it. It is the core HTML.

However, if you want to change color we have to write/maintain our own JS or install the third-party library. I am not sure if it is worth the effort to write/maintain JS to change color when we already have core HTML functionality.

Another option is we can keep only server-side validation (red) which is the core CKAN.

Please let me know what do you think. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop while I was retesting all the UX Enhancement tickets I found one issue with the validation and error message of the IATI Organisation Identifier. This field should accept the - character, currently is expecting numbers and letters only. The error message for both client and server side should say:
_Invalid character detected. Valid characters include letters, numbers and - (dash)._

**Comment by gtkChop** [comment]
@andreaszenasidi Done

**Comment by andreaszenasidi** [comment]
@gtkChop this is still an issue, the client-side validation error message is not correct. The textbox accepts - (dash) so the validation works, only the message is incorrect.
Please use the following error message: _Invalid character detected. Valid characters include letters, numbers and - (dash)._
![image](https://user-images.githubusercontent.com/74558657/150092990-1119a9f5-0c55-4356-a84e-5294aebe43e7.png)

**Comment by gtkChop** [comment]
@andreaszenasidi Done

**Comment by andreaszenasidi** [comment]
@gtkChop looks good, thanks!
