### ISSUE TITLE
Activity dataset's validation status is 'not found'.

### ISSUE THREAD

**Issue by titiolukole** [IATI/ckanext-iati#398]
Hi Cormac/ Jodie, 

The Validation Status is listed as not found. Imperial College of Science, Technology, and Medicine's Activity Dataset's status is "not verified" in the IATI Registry. (See screenshot attached.) 

URL : https://iatiregistry.org/publisher/imperial 

![image](https://user-images.githubusercontent.com/102729339/212125540-f5aec26e-e8ab-4fa3-9cb8-2668b4b92576.png)

**Comment by jodiegardiner** [comment]
Hi @titiolukole,

It says this because the iatistandard validator api returns:

```
{
    "client_error": "The requested report does not exist."
}
```

when it checks for the status for the dataset with id 272c5c23-2592-4283-8a82-5652d0a2f404 (which is this one:
https://iatiregistry.org/dataset/imperial-activities)

**Comment by titiolukole** [comment]
Hi Jodie/ Cormac, 

I had a meeting with Aidstream and uploaded the xml file through the validator itself which came out as successful so I made sure Bibha uploaded in Aidstream which was also successful refreshed everything but then it still came up as not found on the registry which must mean that the registry has a bug. 

The file is still there: https://iatiregistry.org/dataset/imperial-activities 
https://aidstream.s3.us-west-2.amazonaws.com/xml/imperial-activities.xml 

The thought was that If they fetched the validation report again, it would work because they had tried fetching the validation report too early. But once we tried this again, it still didn't work.

**Comment by jodiegardiner** [comment]
To be clear this is still broken and not at our end:

https://api.iatistandard.org/validator/report?hash=272c5c23-2592-4283-8a82-5652d0a2f404

**Comment by titiolukole** [comment]
Hi Jodie,

I have just checked this with our Dev team and the report exists is it possible that the registry is trying to fetch the report at a point before it is generated?  

We also did some tests

This shows the exact timestamp at which this report was generated:
https://validator.iatistandard.org/report/imperial-activities

This shows that the ID's match up 

![image](https://user-images.githubusercontent.com/102729339/214594434-2c225d72-4d3c-4303-b277-e0ca2730e0d8.png)

**Comment by cormachallinanderilinx** [comment]
Hi Titi,

Found the issue and we have pushed the fix to production.

All seems to be good now: 

- Imperial College of Science, Technology, and Medicine https://iatiregistry.org/dataset/imperial-activities 
- Alinea International has a warning but the code seems to be working https://iatiregistry.org/dataset/alineainternational_2020-activities

**Comment by titiolukole** [comment]
Hi Cormac,

Thank you for the update. Can you please fill me in on what the issue was?

Many thanks,


Titi Olukole | Business and data Analyst

Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK

T: +44 (0) 1179 272 505 | M: +44 (7480252441)



At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

________________________________

**Comment by cormachallinanderilinx** [comment]
Hi Titi,

The issue was with IATI validator API key.

We were using it as an environment variable and using pythons os.environ.get() to look it up, which was fine most of the time.

Some of the datasets needed to be updated twice (like the 2 above.
The ckan toolkit was used to call updated package again.
We noticed when it was called using the toolkit it wasnt picking up the Validator key.
We found out that it had to use ckan files and store it in the ckan ini file which is a ckan version of .env files.

We used ckan.config.get() to get the key and it worked in both places

**Comment by titiolukole** [comment]
@cormachallinanderilinx - Issue still persists 

As discussed please see details: 

The two possible solutions are:
1) Set a timer for the Registry to wait 1-2 hours after detecting a change in a dataset before requesting the report.
2) Use the POST /validator/validate endpoint to send the newly updated dataset directly to the Validator to get a fresh report.

1 is easier and would involve much less data transfer, if possible

**Comment by cormachallinanderilinx** [comment]
Hi @titiolukole @akmiller01 

We were looking into this and due to some limitation's of ckan it is not an efficient solution to set an hour timer to re-check.

A possible solution would be to save the ID's of any datasets that fail, set a cron to run at for example 4 am.
It will loop through all the datasets with not found and if it is not a 404 it will update the with the new status.


I really like the 3rd option @akmiller01 suggested too, its quick easy and efficent.

If ye have preferance between the cron job (run at 4 am) OR the 3rd option, please let me know and I will implement it.

**Comment by cormachallinanderilinx** [comment]
Changes have been pushed to staging.
Example you can see the report URL here: https://staging.iatiregistry.org/dataset/jica-289_2014

**Comment by DaveEade49** [comment]
now closed
